### ISSUE TITLE
please remove trackers

### ISSUE THREAD

**Issue by IzzySoft** [1Coin-FinanceTracker/1CoinClient#16]
**Is your feature request related to a problem? Please describe.**
Being a money manager, 1Coin deals with quite personal (and sensible) data – which preferably should be kept private. But the app comes with several tracking libraries included:

```
Offending libs:
---------------
* Crashlytics (/com/crashlytics): NonFreeDep,Tracking
* Firebase Data Transport (/com/google/android/datatransport): NonFreeNet
* Google Mobile Services (/com/google/android/gms): NonFreeDep
* Firebase (/com/google/firebase): NonFreeNet,NonFreeDep
* Firebase Installations (/com/google/firebase/installations): NonFreeNet

5 offenders.
```

All these connect to services run by Google, which is known for collecting data a.o. for "targeted advertising". Not everyone is happy with that.

**Describe the solution you'd like**
Ideally, these tracking libraries should be removed altogether.

**Describe alternatives you've considered**
If analytics are really needed, maybe use [alternatives](https://gitlab.com/-/snippets/1896503#acceptable-analytics) which are not proprietary and which are, hopefully, more privacy-friendly.

**Additional context**
Apart from the tracking aspect, most of the above listed libraries are proprietary. Not sure how they fit with a F/LOSS license :wink:

**Comment by VitalyPeryatin** [comment]
We can't stop collecting analytics data, such as Firebase Crashlytics or Amplitude (you can switch off sending data to Amplitude in app's settings). But we will look at alternatives to not interacting with google servers. We understand that it may be important for some people not to share data with third parties. 

> most of the above listed libraries are proprietary
Could you list which libraries? 

> Not sure how they fit with a F/LOSS license
What license more suitable for our project in your opinion?

**Comment by IzzySoft** [comment]
> we will look at alternatives to not interacting with google servers.

Thanks! Some alternatives are mentioned behind the link I quoted – hopefully one of them will match your needs.

> Could you list which libraries?

I did (those being marked `NonFreeDep` = they are a non-free dependency). The remaining are `NonFreeNet` = "using a non-free network resource", while not necessarily being proprietary code themselves.

> What license more suitable for our project in your opinion?

I rather meant it the other way around: if your project should be free/libre, **any** proprietary component is tainting it and thus should better be avoided. Not always easy, I know – but in most cases possible and even feasible. Cases were it really cannot be avoided are rather very few.

**Comment by IzzySoft** [comment]
No pressure, just want to know where we stand here: is there any chance, @VitalyPeryatin?

**Comment by VitalyPeryatin** [comment]
@IzzySoft 
We aren't going to fix it in the nearest 2 months, because we are focused on fixing bugs and releasing base features. But we will think about this issue later

**Comment by IzzySoft** [comment]
Springtime! Any news on the time line? Any ETA for e.g. a tracker-free build flavor? Again no pressure, just for orientation.

**Comment by VitalyPeryatin** [comment]
So far, there is no progress in this direction

**Comment by IzzySoft** [comment]
But it's still on the list – or do I have to abandon hope?

**Comment by VitalyPeryatin** [comment]
It's still on the list, but with the lowest priority at current time

**Comment by IzzySoft** [comment]
Thanks, then I keep the flame of hope flickering. Wish you the best progress, so you hopefully get to that point soon :wink:

**Comment by CodeCubeNeo** [comment]
Hello. Am am also very much in favor of this.

**Comment by maltsev-gorskij** [comment]
After negotiations within the 1Coin development team, we still decided not to abandon Firebase.
The main reasons for this are as follows:

- Firebase tools used in the project are free for us and are used only to collect information regarding problems that occur during the application usage

- Firebase tools are convenient and familiar to every developer from the core team, as this tools are closely and conveniently integrated with the development environment

- The project is being written on the basis of Kotlin Multiplatform Mobile platform. Firebase Crashlytics also works great in cross-platform. If there are any problems with this library, the solution is found quickly, which speeds up the development of the application

- The application is planned to be published only in stores familiar to most users. The libraries used in the project do not restrict publication in any way. A curious user can go to the “security” tab in the application card in the store at any time. In it, you can also make sure that the application has passed verification and does not transfer any kind of information to third parties

- The team is currently working on releasing Android and iOS version of the app with all the originally planned features that will satisfy most users. Therefore, unfortunately, due to the high load, we will not be able to return to the described issue soon

**Comment by IzzySoft** [comment]
So in short: because it's convenient and cosy, the app will stay non-free (as it includes proprietary libraries) and potentially leak data to Google. No offense meant and definitely no "bad intentions" implied, but as Firebase is not open, **you** can give no guarantee of what it does behind the scenes – you have to believe what a company which lives on data tells you. Apart from which, usage of Google Analytics [does not conform to GDPR](https://iapp.org/news/a/cnil-is-latest-authority-to-rule-google-analytics-violates-gdpr/).

Sad. But for an app that deals with sensitive data (as finances are), from my point of view a no-go. I've linked viable alternatives above, so should you decide to drop the proprietary libs in favor of those, please give me a ping. Until then I'll unfortunately have to black-list 1CoinClient from my inclusion list.
